import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import "./globals.css";

export default function Layout({
  children,
  
}: {
  children: React.ReactNode;
 
}) {

  const geistSans = ({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });
  
  const geistMono = ({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });
  
   const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-blue-50 via-green-50 to-yellow-50`}
      >
        {/* Navigation */}
        <Navbar/>

        {/* Main Content */}
        <main className="flex-1">{children}</main>

        {/* Footer */}
        <Footer/>
      </body>
    </html>
  );
}
